import { GlossaryTerm } from '../types';

export const BIOLOGY_GLOSSARY: GlossaryTerm[] = [
  {
    id: 'action-potential',
    term: 'Action Potential',
    aliases: ['action potentials', 'action-potential', 'membrane depolarization', 'depolarization wavefront', 'neural impulse'],
    category: 'Neurobiology',
    level: 'undergrad',
    pronunciation: '/ˈæk.ʃən pəˈten.ʃəl/',
    etymology: 'Latin actio (doing) + potentia (power)',
    definition: 'A rapid, transient reversal in electrical membrane potential across an excitable cell membrane (neuron or muscle fiber) driven by voltage-gated ion channels.',
    mechanism: 'Resting state (-70mV) depolarizes to threshold (-55mV) opening voltage-gated Na⁺ channels causing rapid Na⁺ influx (depolarization up to +30mV). Voltage-gated K⁺ channels then open as Na⁺ channels inactivate, causing K⁺ efflux (repolarization & hyperpolarization) before Na⁺/K⁺-ATPase restores baseline.',
    clinicalPearl: 'Local anesthetics (e.g. Lidocaine) block voltage-gated Na⁺ channels, halting action potential propagation and pain transmission. Tetrodotoxin (pufferfish) causes lethal paralysis via identical channel blockade.',
    relatedTerms: ['Depolarization', 'Myelin Sheath', 'Synaptic Cleft', 'Neurotransmitter']
  },
  {
    id: 'allosteric-regulation',
    term: 'Allosteric Regulation',
    aliases: ['allosteric', 'allosteric site', 'allosteric modulation', 'allosteric effector', 'allosterism'],
    category: 'Biochemistry',
    level: 'undergrad',
    pronunciation: '/ˌæləˈstɛrɪk ˌrɛɡjʊˈleɪʃən/',
    etymology: 'Greek allos (other) + stereos (solid/structure)',
    definition: 'The regulation of an enzyme or receptor by binding an effector molecule at a distinct site other than the enzyme active site, causing conformational changes.',
    mechanism: 'Effector binding alters tertiary/quaternary protein architecture, shifting between low-affinity (T-state, tense) and high-affinity (R-state, relaxed) states. Positive effectors enhance substrate affinity; negative effectors reduce catalytic rate.',
    clinicalPearl: 'Phosphofructokinase-1 (PFK-1), the key rate-limiting enzyme in glycolysis, is allosterically inhibited by high ATP and citrate, but strongly activated by AMP and Fructose 2,6-bisphosphate.',
    relatedTerms: ['Glycolysis', 'Krebs Cycle', 'ATP Synthase']
  },
  {
    id: 'apoptosis',
    term: 'Apoptosis',
    aliases: ['apoptotic', 'programmed cell death', 'caspase cascade'],
    category: 'Cell & Molecular',
    level: 'undergrad',
    pronunciation: '/ˌæpəpˈtoʊsɪs/ or /ˌeɪpəˈtoʊsɪs/',
    etymology: 'Greek apo (away from) + ptosis (falling)',
    definition: 'Programmed, energy-dependent cell death characterized by cell shrinkage, chromatin condensation, membrane blebbing, and orderly phagocytic engulfment without inflammatory collateral damage.',
    mechanism: 'Can occur via Intrinsic (mitochondrial release of Cytochrome C activating Caspase-9) or Extrinsic (Fas/FasL and TNF-R death receptor pathway activating Caspase-8). Both converge on executioner Caspases-3 and 6.',
    clinicalPearl: 'Evasion of apoptosis (e.g., via p53 tumor suppressor mutation or Bcl-2 overexpression in follicular lymphoma) is a fundamental hallmark of cancer.',
    relatedTerms: ['Mitochondria', 'Phagocytosis']
  },
  {
    id: 'atp-synthase',
    term: 'ATP Synthase',
    aliases: ['ATP synthesis', 'F0F1-ATPase', 'Complex V', 'proton turbine'],
    category: 'Biochemistry',
    level: 'undergrad',
    pronunciation: '/ˌeɪ.tiːˈpiː ˈsɪn.θeɪs/',
    etymology: 'Acronym ATP (Adenosine Triphosphate) + Greek syntheseis (putting together)',
    definition: 'A multi-subunit rotary nanomachine embedded in the inner mitochondrial membrane (and thylakoid membrane) that generates ATP from ADP and inorganic phosphate.',
    mechanism: 'Driven by the proton-motive force (proton gradient generated by Complexes I-IV). Protons traverse the F₀ stator channel, causing the c-ring rotor to rotate, driving conformational cycling in the catalytic F₁ head (Open, Loose, Tight) to synthesize ATP.',
    clinicalPearl: 'Oligomycin inhibits the F₀ subunit directly, arresting ATP generation and halting the entire electron transport chain via high membrane proton back-pressure.',
    relatedTerms: ['Mitochondria', 'Oxidative Phosphorylation', 'Krebs Cycle']
  },
  {
    id: 'bohr-effect',
    term: 'Bohr Effect',
    aliases: ['Bohr shift', 'Bohr effect', 'O2 dissociation curve shift'],
    category: 'Physiology',
    level: 'undergrad',
    pronunciation: '/ˈbɔːr ɪˌfɛkt/',
    etymology: 'Named after Danish physiologist Christian Bohr (1904)',
    definition: 'A physiological phenomenon wherein increases in carbon dioxide concentration, acidity (lower pH), temperature, and 2,3-BPG decrease hemoglobin oxygen affinity, promoting O₂ delivery to metabolically active tissues.',
    mechanism: 'Protons (H⁺) bind to specific histidine residues on deoxygenated hemoglobin, forming salt bridges that stabilize the low-affinity T-state (Tense conformation), shifting the oxyhemoglobin dissociation curve to the right.',
    clinicalPearl: 'Mnemonic: "CADET face Right!" - CO₂, Acidity (H⁺), 2,3-DPG, Exercise, and Temperature shift the oxygen dissociation curve to the RIGHT (enhancing tissue oxygen unloading).',
    relatedTerms: ['Hemoglobin', 'Haldane Effect']
  },
  {
    id: 'cardiomyocyte',
    term: 'Cardiomyocyte',
    aliases: ['cardiomyocytes', 'cardiac muscle cells', 'cardiac myocyte', 'myocardiocyte'],
    category: 'Anatomy',
    level: 'undergrad',
    pronunciation: '/ˌkɑːr.di.oʊˈmaɪ.ə.saɪt/',
    etymology: 'Greek kardia (heart) + mys (muscle) + kytos (cell)',
    definition: 'Specialized, branched striated muscle cells of the heart that contract rhythmically and involuntarily to pump blood through the circulatory system.',
    mechanism: 'Connected by intercalated discs containing desmosomes (for mechanical strength) and gap junctions (connexons) which permit low-resistance electrical current flow, allowing the myocardium to act as a functional syncytium.',
    clinicalPearl: 'Elevated serum Troponin I and Troponin T are gold-standard biomarkers for cardiomyocyte necrosis during an acute myocardial infarction (heart attack).',
    relatedTerms: ['Troponin', 'Action Potential', 'Sarcomere']
  },
  {
    id: 'complement-system',
    term: 'Complement System',
    aliases: ['complement cascade', 'membrane attack complex', 'opsonization', 'C3b', 'C5b-9'],
    category: 'Immunology',
    level: 'grad',
    pronunciation: '/ˈkɒm.plɪ.mənt ˈsɪs.təm/',
    etymology: 'Latin complementum (that which completes/fills up)',
    definition: 'A cascade of over 30 soluble plasma and cell-surface proteins that enhances (complements) the ability of antibodies and phagocytes to clear pathogens and damaged cells.',
    mechanism: 'Activated via Classical (antibody-antigen complexes), Lectin (mannose-binding lectin), or Alternative (spontaneous C3 hydrolysis) pathways. All cleave C3 into C3a (anaphylatoxin) and C3b (opsonin), converging to generate C5b-9 (Membrane Attack Complex) that lyses target cells.',
    clinicalPearl: 'Deficiencies in terminal complement factors C5-C9 result in recurrent, life-threatening Neisseria meningitidis and Neisseria gonorrhoeae infections due to inability to form the Membrane Attack Complex.',
    relatedTerms: ['Phagocytosis', 'Macrophage']
  },
  {
    id: 'countercurrent-multiplier',
    term: 'Countercurrent Multiplier',
    aliases: ['countercurrent mechanism', 'medullary osmotic gradient', 'loop of Henle concentration'],
    category: 'Physiology',
    level: 'grad',
    pronunciation: '/ˌkaʊn.tərˈkʌr.ənt ˈmʌl.tɪ.plaɪ.ər/',
    etymology: 'English counter + current + multiplier',
    definition: 'The renal mechanism in the Loop of Henle and vasa recta that establishes an osmotic gradient (300 to 1200 mOsm/kg) in the renal medulla to concentrate urine.',
    mechanism: 'The descending thin limb is water-permeable and solute-impermeable (water exits via AQP1). The thick ascending limb actively pumps Na⁺/K⁺/2Cl⁻ out into the interstitium (NKCC2) and is impermeable to water, progressively multiplying the hypertonicity deeper into the inner medulla.',
    clinicalPearl: 'Loop diuretics (e.g. Furosemide) inhibit the NKCC2 co-transporter in the thick ascending limb, abolishing the medullary osmotic gradient and causing profound diuresis.',
    relatedTerms: ['Glomerulus', 'Podocyte', 'Juxtaglomerular Apparatus']
  },
  {
    id: 'crispr-cas9',
    term: 'CRISPR-Cas9',
    aliases: ['CRISPR', 'Cas9', 'guide RNA', 'gene editing', 'CRISPR/Cas'],
    category: 'Genetics',
    level: 'school',
    pronunciation: '/ˈkrɪs.pər kæs naɪn/',
    etymology: 'Clustered Regularly Interspaced Short Palindromic Repeats + CRISPR-associated protein 9',
    definition: 'A microbial adaptive immune system engineered into a precise molecular biology tool for targeted genome editing in living organisms.',
    mechanism: 'A single guide RNA (sgRNA) matches a 20-nucleotide target genomic sequence adjacent to a Protospacer Adjacent Motif (PAM). Cas9 endonuclease binds and induces a double-strand break (DSB), prompting either non-homologous end joining (NHEJ, gene knockout) or homology-directed repair (HDR, gene knock-in).',
    clinicalPearl: 'CRISPR-based therapeutics (e.g., Casgevy) are approved for Sickle Cell Disease and Beta-Thalassemia by reactivating fetal hemoglobin (HbF) through BCL11A enhancer disruption.',
    relatedTerms: ['Transcription Factor', 'Okazaki Fragments']
  },
  {
    id: 'depolarization',
    term: 'Depolarization',
    aliases: ['depolarized', 'depolarizing', 'membrane depolarization', 'depolarization phase'],
    category: 'Physiology',
    level: 'school',
    pronunciation: '/diːˌpoʊ.lə.rɪˈzeɪ.ʃən/',
    etymology: 'Prefix de- (undo) + polarization',
    definition: 'A shift in a cell membrane electrical charge distribution, making the inside of the cell less negative (or positive) relative to the outside.',
    mechanism: 'Typically caused by opening of cation-permeable channels (such as voltage-gated Na⁺ or Ca²⁺ channels), allowing positive ions to rush down their electrochemical gradient into the cytoplasm.',
    clinicalPearl: 'Hyperkalemia (high serum K⁺) reduces the concentration gradient for K⁺ efflux, partially depolarizing cardiac resting membrane potential and predisposing to fatal arrhythmias (sine wave ECG).',
    relatedTerms: ['Action Potential', 'Synaptic Cleft', 'Cardiomyocyte']
  },
  {
    id: 'endoplasmic-reticulum',
    term: 'Endoplasmic Reticulum',
    aliases: ['endoplasmic reticulum', 'rough ER', 'smooth ER', 'RER', 'SER', 'sarcoplasmic reticulum'],
    category: 'Cell & Molecular',
    level: 'school',
    pronunciation: '/ˌɛn.doʊˈplæz.mɪk rɪˈtɪk.jʊ.ləm/',
    etymology: 'Greek endon (within) + plasma (formed) + Latin reticulum (little net)',
    definition: 'A continuous membrane network of cisternae and tubules involved in protein synthesis and modification (Rough ER) and lipid synthesis, steroid metabolism, and drug detoxification (Smooth ER).',
    mechanism: 'Rough ER is studded with ribosomes for synthesizing membrane and secretory proteins, undergoing N-linked glycosylation. Smooth ER synthesizes phospholipids/steroids and sequesters intracellular Ca²⁺ (sarcoplasmic reticulum in muscle).',
    clinicalPearl: 'Prolonged unfolded protein accumulation in the ER triggers the "Unfolded Protein Response" (UPR), which if unmitigated leads to caspase activation and apoptosis.',
    relatedTerms: ['Ribosome', 'Golgi Apparatus', 'Mitochondria']
  },
  {
    id: 'glomerular-filtration-rate',
    term: 'Glomerular Filtration Rate (GFR)',
    aliases: ['GFR', 'eGFR', 'glomerular filtration', 'renal clearance'],
    category: 'Physiology',
    level: 'undergrad',
    pronunciation: '/ɡloʊˈmɛr.jʊ.lər fɪlˈtreɪ.ʃən reɪt/',
    etymology: 'Latin glomus (ball of yarn) + filtration',
    definition: 'The total volume of fluid filtered from the renal glomerular capillaries into Bowman capsule per unit time (normally ~120-125 mL/min in healthy adults).',
    mechanism: 'Determined by Starling forces: GFR = Kf × [(Pgc - Pbs) - (πgc - πbs)], where Pgc is glomerular capillary hydrostatic pressure, Pbs is Bowman space hydrostatic pressure, and πgc is capillary oncotic pressure.',
    clinicalPearl: 'Serum Creatinine and Inulin/Cystatin C clearance are used to estimate GFR. Chronic Kidney Disease (CKD) stages 1-5 are clinically classified by GFR thresholds (e.g. Stage 5 GFR < 15 mL/min).',
    relatedTerms: ['Glomerulus', 'Podocyte', 'Countercurrent Multiplier', 'Juxtaglomerular Apparatus']
  },
  {
    id: 'glomerulus',
    term: 'Glomerulus',
    aliases: ['glomeruli', 'glomerular capillary', 'glomerular tuft', 'Bowman capsule'],
    category: 'Anatomy',
    level: 'school',
    pronunciation: '/ɡloʊˈmɛr.jʊ.ləs/',
    etymology: 'Latin glomus (ball of yarn) + diminutive -ulus',
    definition: 'A microscopic tuft of fenestrated capillaries located at the beginning of a nephron in the kidney, responsible for filtering plasma into Bowman capsule.',
    mechanism: 'Filtration barrier consists of three layers: fenestrated capillary endothelium, negatively charged glomerular basement membrane (heparan sulfate), and podocyte foot processes with slit diaphragms.',
    clinicalPearl: 'Nephrotic syndrome is characterized by podocyte effacement or basement membrane damage leading to massive proteinuria (>3.5 g/day), hypoalbuminemia, and peripheral edema.',
    relatedTerms: ['Podocyte', 'Juxtaglomerular Apparatus', 'Countercurrent Multiplier']
  },
  {
    id: 'glycolysis',
    term: 'Glycolysis',
    aliases: ['glycolytic pathway', 'Embden-Meyerhof pathway', 'glucose breakdown'],
    category: 'Biochemistry',
    level: 'school',
    pronunciation: '/ɡlaɪˈkɒl.ə.sɪs/',
    etymology: 'Greek glykys (sweet) + lysis (splitting)',
    definition: 'A 10-step anaerobic metabolic pathway in the cytoplasm that breaks down 1 molecule of glucose into 2 molecules of pyruvate, yielding a net of 2 ATP and 2 NADH.',
    mechanism: 'Comprises an energy investment phase (consuming 2 ATP via Hexokinase and PFK-1) and an energy payoff phase (producing 4 ATP and 2 NADH via substrate-level phosphorylation).',
    clinicalPearl: 'Warburg effect: Cancer cells preferentially utilize glycolysis for ATP generation even in the presence of abundant oxygen (aerobic glycolysis), visualized on FDG-PET imaging.',
    relatedTerms: ['Krebs Cycle', 'ATP Synthase', 'Allosteric Regulation']
  },
  {
    id: 'gpcr',
    term: 'G-Protein Coupled Receptor (GPCR)',
    aliases: ['GPCR', 'GPCRs', '7-transmembrane receptor', 'heptahelical receptor', 'G protein-coupled receptor'],
    category: 'Biochemistry',
    level: 'grad',
    pronunciation: '/ˌdʒiː.proʊ.tiːn ˈkʌp.əld rɪˈsɛp.tər/',
    etymology: 'Guanine nucleotide-binding protein coupled',
    definition: 'The largest family of 7-transmembrane domain cell surface receptors that transduce extracellular signals into intracellular responses via heterotrimeric G-proteins (Gα, Gβ, Gγ).',
    mechanism: 'Ligand binding induces conformational shift, promoting GDP-to-GTP exchange on the Gα subunit. Gα-GTP dissociates to activate second messenger effectors: Gαs stimulates adenylyl cyclase (cAMP ↑), Gαi inhibits adenylyl cyclase (cAMP ↓), and Gαq activates Phospholipase C (IP3/DAG/Ca²⁺ ↑).',
    clinicalPearl: 'Over 30% of all FDA-approved prescription drugs (including beta-blockers, antihistamines, and opioid analgesics) target GPCRs.',
    relatedTerms: ['Action Potential', 'Synaptic Cleft']
  },
  {
    id: 'hemoglobin',
    term: 'Hemoglobin',
    aliases: ['haemoglobin', 'Hb', 'oxyhemoglobin', 'deoxyhemoglobin', 'carbaminohemoglobin'],
    category: 'Biochemistry',
    level: 'school',
    pronunciation: '/ˈhiː.məˌɡloʊ.bɪn/',
    etymology: 'Greek haima (blood) + Latin globus (sphere)',
    definition: 'A tetrameric metalloprotein in red blood cells consisting of four globin chains (2 alpha, 2 beta in adult HbA), each containing an iron-bearing heme group capable of reversibly binding molecular oxygen (O₂).',
    mechanism: 'Exhibits positive cooperativity: binding of the first O₂ molecule to one heme iron shifts quaternary structure from the low-affinity T (tense) state to the high-affinity R (relaxed) state, yielding a sigmoidal binding curve.',
    clinicalPearl: 'Sickle cell disease is caused by a single missense point mutation in the beta-globin gene (glutamic acid to valine at position 6, E6V), causing deoxygenated HbS polymerisation into sickle strands.',
    relatedTerms: ['Bohr Effect', 'Cardiomyocyte']
  },
  {
    id: 'homeostasis',
    term: 'Homeostasis',
    aliases: ['homeostatic', 'homeostatic regulation', 'internal equilibrium'],
    category: 'Physiology',
    level: 'school',
    pronunciation: '/ˌhoʊ.mi.oʊˈsteɪ.sɪs/',
    etymology: 'Greek homoios (similar) + stasis (standing still)',
    definition: 'The dynamic physiological process by which living organisms maintain stable, optimal internal conditions (pH, body temperature, osmolarity, blood glucose) despite external perturbations.',
    mechanism: 'Operates predominantly via negative feedback loops: a sensor/receptor detects deviations from a set-point, an integrator/control center calculates the response, and effectors trigger corrective actions.',
    clinicalPearl: 'Diabetic Ketoacidosis (DKA) represents severe homeostatic failure: absolute insulin deficiency disrupts glucose balance, driving unchecked lipolysis, ketogenesis, and life-threatening metabolic acidosis.',
    relatedTerms: ['Osmosis', 'Renin-Angiotensin-Aldosterone System (RAAS)']
  },
  {
    id: 'juxtaglomerular-apparatus',
    term: 'Juxtaglomerular Apparatus (JGA)',
    aliases: ['JGA', 'juxtaglomerular cells', 'macula densa', 'JG cells'],
    category: 'Anatomy',
    level: 'grad',
    pronunciation: '/ˌdʒʌk.stə.ɡloʊˈmɛr.jʊ.lər æp.əˈreɪ.təs/',
    etymology: 'Latin juxta (near) + glomerulus + apparatus',
    definition: 'A specialized microscopic structure in the kidney situated between the vascular pole of the renal corpuscle and the returning distal convoluted tubule, regulating blood pressure and GFR.',
    mechanism: 'Composed of Macula Densa cells (chemoreceptors sensing tubular Na⁺/Cl⁻ load), Juxtaglomerular/Granular cells (modified smooth muscle secreting Renin), and Extraglomerular Mesangial cells. Low tubular NaCl stimulates Renin secretion.',
    clinicalPearl: 'Renal artery stenosis triggers excessive renin release from the JGA due to perceived low renal perfusion pressure, causing renovascular hypertension (Goldblatt kidney).',
    relatedTerms: ['Glomerulus', 'Renin-Angiotensin-Aldosterone System (RAAS)', 'Glomerular Filtration Rate (GFR)']
  },
  {
    id: 'krebs-cycle',
    term: 'Krebs Cycle (Citric Acid Cycle)',
    aliases: ['TCA cycle', 'tricarboxylic acid cycle', 'citric acid cycle'],
    category: 'Biochemistry',
    level: 'school',
    pronunciation: '/ˈkrɛbz ˈsaɪ.kəl/',
    etymology: 'Named after biochemist Hans Adolf Krebs (1937)',
    definition: 'An 8-step cyclical series of enzymatic reactions in the mitochondrial matrix that oxidizes acetyl-CoA into CO₂, generating high-energy electron carriers (NADH, FADH₂) and GTP/ATP.',
    mechanism: 'Acetyl-CoA (2C) condenses with Oxaloacetate (4C) via Citrate Synthase to form Citrate (6C). Per turn: yields 3 NADH, 1 FADH₂, 1 GTP (ATP), and 2 CO₂. Isocitrate dehydrogenase is the rate-limiting enzyme.',
    clinicalPearl: 'Fluoroacetate (found in rat poison) is metabolized into fluorocitrate, which irreversibly inhibits aconitase, shutting down the Krebs cycle and causing rapid cellular death.',
    relatedTerms: ['Glycolysis', 'ATP Synthase', 'Mitochondria']
  },
  {
    id: 'macrophage',
    term: 'Macrophage',
    aliases: ['macrophages', 'histiocyte', 'monocyte-macrophage', 'phagocytic cells'],
    category: 'Immunology',
    level: 'school',
    pronunciation: '/ˈmæk.rə.feɪdʒ/',
    etymology: 'Greek makros (large) + phagein (to eat)',
    definition: 'Large, specialized tissue-resident phagocytic leukocytes derived from circulating monocytes that ingest foreign pathogens, cellular debris, and present antigens to T cells.',
    mechanism: 'Recognize pathogen-associated molecular patterns (PAMPs) via Pattern Recognition Receptors (e.g. Toll-Like Receptors / TLRs). Internalize prey into phagosomes, which fuse with lysosomes to produce phagolysosomes for reactive oxygen species (ROS) degradation.',
    clinicalPearl: 'Macrophages can differentiate into M1 (pro-inflammatory, killer) or M2 (anti-inflammatory, tissue repair) phenotypes. In tuberculosis, lipid-laden macrophages transform into epithelioid cells forming caseating granulomas.',
    relatedTerms: ['Phagocytosis', 'Complement System']
  },
  {
    id: 'mhc-class-i-ii',
    term: 'MHC Class I & II',
    aliases: ['MHC', 'major histocompatibility complex', 'HLA', 'human leukocyte antigen', 'MHC-I', 'MHC-II'],
    category: 'Immunology',
    level: 'grad',
    pronunciation: '/ˌem.eɪtʃˈsiː/',
    etymology: 'Major Histocompatibility Complex',
    definition: 'Cell surface glycoproteins that display peptide antigens to T-lymphocytes, governing adaptive immune recognition and self vs. non-self discrimination.',
    mechanism: 'MHC Class I is present on ALL nucleated cells and presents endogenous antigens (viral/tumor) to CD8⁺ cytotoxic T cells. MHC Class II is restricted to professional antigen-presenting cells (dendritic cells, macrophages, B cells) and presents exogenous antigens to CD4⁺ helper T cells.',
    clinicalPearl: 'Rule of 8: CD8 × MHC I = 8; CD4 × MHC II = 8. Specific HLA alleles correlate strongly with autoimmune diseases (e.g., HLA-B27 with Ankylosing Spondylitis; HLA-DQ2/DQ8 with Celiac Disease).',
    relatedTerms: ['Macrophage', 'Phagocytosis']
  },
  {
    id: 'mitochondria',
    term: 'Mitochondria',
    aliases: ['mitochondrion', 'mitochondrial', 'cristae', 'mitochondrial matrix'],
    category: 'Cell & Molecular',
    level: 'school',
    pronunciation: '/ˌmaɪ.təˈkɒn.dri.ə/',
    etymology: 'Greek mitos (thread) + chondrion (small grain)',
    definition: 'Double-membrane-bound eukaryotic organelles responsible for cellular respiration, generating the vast majority of cellular ATP via oxidative phosphorylation.',
    mechanism: 'Consists of an outer membrane, intermembrane space (where protons accumulate), inner membrane with folded cristae housing the Electron Transport Chain (Complexes I-IV + ATP Synthase), and the mitochondrial matrix.',
    clinicalPearl: 'Mitochondrial DNA (mtDNA) is inherited exclusively through the maternal lineage. Mutations cause systemic mitochondrial myopathies (e.g., MELAS, MERRF) characterized by "ragged red fibers" on muscle biopsy.',
    relatedTerms: ['ATP Synthase', 'Krebs Cycle', 'Apoptosis']
  },
  {
    id: 'myelin-sheath',
    term: 'Myelin Sheath',
    aliases: ['myelin', 'myelination', 'myelinated axons', 'Schwann cells', 'oligodendrocytes', 'nodes of Ranvier'],
    category: 'Anatomy',
    level: 'school',
    pronunciation: '/ˈmaɪ.ə.lɪn ʃiːθ/',
    etymology: 'Greek myelos (marrow) + Old English sceath',
    definition: 'A lipid-rich dielectric insulating layer surrounding neuronal axons, produced by Schwann cells in the PNS and Oligodendrocytes in the CNS.',
    mechanism: 'Increases membrane resistance and decreases capacitance, forcing electrical depolarization to jump rapidly between uninsulated gaps called Nodes of Ranvier (saltatory conduction), accelerating conduction velocity up to 100-fold.',
    clinicalPearl: 'Multiple Sclerosis (MS) is an autoimmune demyelinating disease of the CNS (oligodendrocytes), while Guillain-Barré syndrome attacks PNS myelin (Schwann cells) following Campylobacter or viral infection.',
    relatedTerms: ['Action Potential', 'Synaptic Cleft']
  },
  {
    id: 'nephron',
    term: 'Nephron',
    aliases: ['nephrons', 'renal nephron', 'proximal tubule', 'distal tubule', 'collecting duct'],
    category: 'Anatomy',
    level: 'school',
    pronunciation: '/ˈnɛf.rɒn/',
    etymology: 'Greek nephros (kidney)',
    definition: 'The fundamental microscopic functional structural unit of the kidney (~1 million per kidney) that filters blood, reabsorbs essential nutrients and water, and excretes metabolic waste as urine.',
    mechanism: 'Composed of the renal corpuscle (Glomerulus + Bowman capsule), Proximal Convoluted Tubule (reabsorbing ~65% of water and electrolytes, 100% of glucose and amino acids), Loop of Henle, Distal Convoluted Tubule, and Collecting Duct.',
    clinicalPearl: 'Glucosuria occurs when blood glucose exceeds the renal threshold (~180-200 mg/dL), saturating sodium-glucose cotransporters (SGLT2) in the proximal convoluted tubule.',
    relatedTerms: ['Glomerulus', 'Podocyte', 'Countercurrent Multiplier', 'Juxtaglomerular Apparatus']
  },
  {
    id: 'neurotransmitter',
    term: 'Neurotransmitter',
    aliases: ['neurotransmitters', 'neuromodulator', 'acetylcholine', 'dopamine', 'GABA', 'glutamate', 'serotonin'],
    category: 'Neurobiology',
    level: 'school',
    pronunciation: '/ˌnjʊə.roʊ.trænzˈmɪt.ər/',
    etymology: 'Greek neuron (nerve) + Latin transmittere (send across)',
    definition: 'Endogenous chemical signaling messengers packaged in synaptic vesicles that transmit signals across a chemical synapse from a presynaptic neuron to a postsynaptic target cell.',
    mechanism: 'Depolarization opens voltage-gated Ca²⁺ channels at the axon terminal; Ca²⁺ influx triggers SNARE-complex-mediated vesicle fusion and exocytosis into the synaptic cleft, binding ionotropic or metabotropic receptors.',
    clinicalPearl: 'Myasthenia Gravis is an autoimmune disorder in which autoantibodies attack postsynaptic Nicotinic Acetylcholine Receptors (AChR) at neuromuscular junctions, causing progressive muscle weakness relieved by acetylcholinesterase inhibitors (e.g., Pyridostigmine).',
    relatedTerms: ['Synaptic Cleft', 'Action Potential', 'GPCR']
  },
  {
    id: 'okazaki-fragments',
    term: 'Okazaki Fragments',
    aliases: ['Okazaki fragment', 'lagging strand synthesis', 'DNA ligase', 'RNA primer'],
    category: 'Genetics',
    level: 'undergrad',
    pronunciation: '/ˌoʊ.kəˈzɑː.ki ˈfræɡ.mənts/',
    etymology: 'Named after Japanese molecular biologists Reiji and Tsuneko Okazaki (1968)',
    definition: 'Short, discontinuous segments of synthesized DNA (100-200 nucleotides in eukaryotes) produced on the lagging template strand during DNA replication.',
    mechanism: 'Because DNA Polymerase can only synthesize in the 5\' to 3\' direction, the lagging strand unwinds in the opposite direction, requiring repeated RNA primers laid down by Primase. DNA Polymerase synthesizes Okazaki fragments, DNA Pol I removes primers, and DNA Ligase seals the phosphodiester nicks.',
    clinicalPearl: 'Fluoroquinolone antibiotics (e.g., Ciprofloxacin) inhibit bacterial DNA Gyrase (Topoisomerase II) and Topoisomerase IV, preventing replication fork progression and stalling Okazaki fragment ligation.',
    relatedTerms: ['CRISPR-Cas9', 'Transcription Factor']
  },
  {
    id: 'osmosis',
    term: 'Osmosis',
    aliases: ['osmotic', 'osmolarity', 'osmolality', 'oncotic pressure', 'tonicity', 'hypotonic', 'hypertonic', 'isotonic'],
    category: 'Physiology',
    level: 'school',
    pronunciation: '/ɒzˈmoʊ.sɪs/',
    etymology: 'Greek osmos (a push or thrust)',
    definition: 'The net passive movement of solvent molecules (typically water) through a selectively permeable membrane from a region of lower solute concentration to a region of higher solute concentration.',
    mechanism: 'Facilitated across cell membranes by aquaporin channels. Water flows down its chemical potential gradient until hydrostatic pressure balances osmotic pressure.',
    clinicalPearl: 'Rapid correction of chronic hyponatremia with hypertonic saline can cause Osmotic Demyelination Syndrome (Central Pontine Myelinolysis), leading to irreversible quadriplegia and "locked-in" syndrome.',
    relatedTerms: ['Homeostasis', 'Glomerular Filtration Rate (GFR)']
  },
  {
    id: 'phagocytosis',
    term: 'Phagocytosis',
    aliases: ['phagocytic', 'phagocytose', 'phagosome', 'phagolysosome', 'cell eating'],
    category: 'Immunology',
    level: 'school',
    pronunciation: '/ˌfæɡ.ə.saɪˈtoʊ.sɪs/',
    etymology: 'Greek phagein (to devour) + kytos (cell) + -osis (process)',
    definition: 'A specialized form of endocytosis by which a cell (such as a macrophage, neutrophil, or dendritic cell) engulfs large particulate matter, microorganisms, or apoptotic bodies.',
    mechanism: 'Actin cytoskeleton polymerization extends pseudopods around the target, enclosing it within an intracellular vesicle called a phagosome. The phagosome fuses with a lysosome to form a phagolysosome, where acid hydrolases and NADPH oxidase-derived superoxide radicals degrade the ingested material.',
    clinicalPearl: 'Chronic Granulomatous Disease (CGD) is an X-linked immunodeficiency caused by NADPH oxidase deficiency, impairing the phagocyte respiratory burst and predisposing to recurrent catalase-positive infections (e.g. S. aureus, Aspergillus).',
    relatedTerms: ['Macrophage', 'Complement System', 'Apoptosis']
  },
  {
    id: 'podocyte',
    term: 'Podocyte',
    aliases: ['podocytes', 'visceral epithelial cells', 'foot processes', 'pedicels', 'slit diaphragm'],
    category: 'Anatomy',
    level: 'grad',
    pronunciation: '/ˈpɒd.ə.saɪt/',
    etymology: 'Greek podos (foot) + kytos (cell)',
    definition: 'Highly differentiated, octopus-like epithelial cells lining the visceral layer of Bowman capsule in the kidney that interdigitate with neighboring cells to form the ultimate filtration slit barrier.',
    mechanism: 'Extend primary trabeculae and secondary interdigitating foot processes (pedicels) wrapped around glomerular capillaries. Slit diaphragms composed of Nephrin and Podocin form ~25-30 nm pores with negative surface charge that prevent albumin filtration.',
    clinicalPearl: 'Minimal Change Disease (the most common cause of nephrotic syndrome in children) is characterized by diffuse effacement (flattening/loss) of podocyte foot processes visible only on electron microscopy.',
    relatedTerms: ['Glomerulus', 'Glomerular Filtration Rate (GFR)', 'Nephron']
  },
  {
    id: 'raas',
    term: 'Renin-Angiotensin-Aldosterone System (RAAS)',
    aliases: ['RAAS', 'angiotensin', 'aldosterone', 'renin-angiotensin', 'ACE', 'angiotensin II'],
    category: 'Physiology',
    level: 'undergrad',
    pronunciation: '/ˈriː.nɪn ˌæn.dʒi.oʊˈtɛn.sɪn ælˈdɒs.tə.roʊn ˈsɪs.təm/',
    etymology: 'Renin (kidney enzyme) + Angio (vessel) + Tensin (tension) + Aldosterone (steroid)',
    definition: 'A multi-organ hormonal endocrine cascade that regulates systemic arterial blood pressure, renal hemodynamics, intravascular volume, and sodium-potassium balance.',
    mechanism: 'Low renal perfusion triggers Renin secretion by JGA cells. Renin cleaves liver Angiotensinogen to Angiotensin I. Angiotensin-Converting Enzyme (ACE) in pulmonary vascular endothelium converts Ang I to Angiotensin II (a potent vasoconstrictor that triggers Aldosterone release from the adrenal cortex).',
    clinicalPearl: 'ACE inhibitors (e.g. Lisinopril) and ARBs (e.g. Losartan) are foundational first-line drugs for hypertension, heart failure, and diabetic nephropathy by blunting RAAS-mediated efferent arteriolar constriction.',
    relatedTerms: ['Juxtaglomerular Apparatus', 'Glomerular Filtration Rate (GFR)', 'Vasoconstriction']
  },
  {
    id: 'ribosome',
    term: 'Ribosome',
    aliases: ['ribosomes', 'ribosomal subunits', 'polyribosome', 'polysome', '70S', '80S'],
    category: 'Cell & Molecular',
    level: 'school',
    pronunciation: '/ˈraɪ.bə.soʊm/',
    etymology: 'Ribonucleic acid + Greek soma (body)',
    definition: 'A universal ribonucleoprotein complex composed of ribosomal RNA (rRNA) and proteins that translates messenger RNA (mRNA) sequences into polypeptide chains.',
    mechanism: 'Eukaryotes have 80S ribosomes (60S large and 40S small subunits); prokaryotes have 70S (50S and 30S). The ribosome reads mRNA codons at the A (aminoacyl), P (peptidyl), and E (exit) sites, catalyzing peptide bond formation via peptidyl transferase activity.',
    clinicalPearl: 'Bacterial 70S ribosomes are the selective targets for major antibiotic classes: Macrolides and Clindamycin inhibit 50S; Aminoglycosides and Tetracyclines inhibit 30S.',
    relatedTerms: ['Endoplasmic Reticulum', 'Transcription Factor']
  },
  {
    id: 'sarcomere',
    term: 'Sarcomere',
    aliases: ['sarcomeres', 'Z-disc', 'actin-myosin', 'sliding filament', 'A-band', 'I-band'],
    category: 'Physiology',
    level: 'undergrad',
    pronunciation: '/ˈsɑːr.kə.mɪər/',
    etymology: 'Greek sarx (flesh) + meros (part)',
    definition: 'The fundamental repeating contractile functional unit of striated muscle tissue (skeletal and cardiac), bounded by two consecutive Z-discs.',
    mechanism: 'According to the Sliding Filament Theory: Ca²⁺ binds Troponin C, shifting Tropomyosin off actin binding sites. Myosin heads hydrolyze ATP, bind actin forming cross-bridges, perform the power stroke pulling actin inward, and release upon binding fresh ATP.',
    clinicalPearl: 'Rigor mortis occurs post-mortem because ATP depletion prevents Myosin heads from detaching from Actin filaments, leaving muscles fixed in a rigid contracted state.',
    relatedTerms: ['Troponin', 'Cardiomyocyte', 'Action Potential']
  },
  {
    id: 'surfactant',
    term: 'Pulmonary Surfactant',
    aliases: ['surfactant', 'dipalmitoylphosphatidylcholine', 'DPPC', 'type II pneumocytes'],
    category: 'Physiology',
    level: 'undergrad',
    pronunciation: '/pʌlˈmɒn.ər.i sɜːrˈfæk.tənt/',
    etymology: 'Surface active agent',
    definition: 'A complex mixture of phospholipids (predominantly DPPC) and surfactant proteins (SP-A, B, C, D) secreted by Type II alveolar pneumocytes in the lungs.',
    mechanism: 'Intersperses between water molecules lining the alveolar air-liquid interface, dramatically reducing surface tension. According to the Law of Laplace (P = 2T/r), lowering surface tension prevents smaller alveoli from collapsing during expiration and decreases the work of breathing.',
    clinicalPearl: 'Neonatal Respiratory Distress Syndrome (NRDS) occurs in premature infants due to surfactant deficiency (insufficient Type II pneumocyte maturity before 35 weeks gestation), presenting with ground-glass reticular infiltrates on chest X-ray.',
    relatedTerms: ['Homeostasis', 'Bohr Effect']
  },
  {
    id: 'synaptic-cleft',
    term: 'Synaptic Cleft',
    aliases: ['synapse', 'synaptic junction', 'chemical synapse', 'presynaptic terminal', 'postsynaptic density'],
    category: 'Neurobiology',
    level: 'school',
    pronunciation: '/sɪˈnæp.tɪk klɛft/',
    etymology: 'Greek synapsis (junction/contact) + Old English cliofan (split)',
    definition: 'The microscopic extracellular physical gap (~20-40 nm wide) between the presynaptic axon terminal and the postsynaptic neuron, muscle, or gland cell.',
    mechanism: 'Neurotransmitters diffuse across this aqueous gap in under 1 millisecond, binding to ligand-gated ion channels or GPCRs on the postsynaptic membrane to generate excitatory (EPSP) or inhibitory (IPSP) postsynaptic potentials.',
    clinicalPearl: 'Botulinum toxin cleaves presynaptic SNARE proteins (SNAP-25 / Synaptobrevin), blocking acetylcholine release into the synaptic cleft and causing flaccid paralysis.',
    relatedTerms: ['Neurotransmitter', 'Action Potential', 'GPCR']
  },
  {
    id: 'transcription-factor',
    term: 'Transcription Factor',
    aliases: ['transcription factors', 'TF', 'enhancer binding protein', 'zinc finger', 'leucine zipper'],
    category: 'Genetics',
    level: 'undergrad',
    pronunciation: '/trænˈskrɪp.ʃən ˈfæk.tər/',
    etymology: 'Latin transcribere (to write over/copy) + factor (maker)',
    definition: 'A protein that controls the rate of transcription of genetic information from DNA to messenger RNA by binding to specific DNA promoter or enhancer sequences.',
    mechanism: 'Contains DNA-binding domains (e.g., helix-turn-helix, zinc finger, basic leucine zipper) and transactivation domains that recruit or block RNA Polymerase II and histone-modifying coactivators/corepressors.',
    clinicalPearl: 'p53 is the "guardian of the genome" transcription factor that upregulates p21 (cell cycle arrest) and BAX (apoptosis) in response to DNA damage; mutated in >50% of all human cancers.',
    relatedTerms: ['CRISPR-Cas9', 'Apoptosis', 'Okazaki Fragments']
  },
  {
    id: 'troponin',
    term: 'Troponin',
    aliases: ['troponin complex', 'Troponin I', 'Troponin T', 'Troponin C', 'TnI', 'TnT', 'TnC'],
    category: 'Biochemistry',
    level: 'undergrad',
    pronunciation: '/ˈtroʊ.pə.nɪn/',
    etymology: 'Greek tropos (turn/manner)',
    definition: 'A regulatory heterotrimeric protein complex (TnT, TnI, TnC) anchored to tropomyosin on thin actin filaments of cardiac and skeletal muscle fibers.',
    mechanism: 'Troponin C binds intracellular Ca²⁺ ions, inducing a conformational change that pulls Tropomyosin away from the myosin-binding sites on actin filaments, allowing cross-bridge cycling and muscle contraction to proceed.',
    clinicalPearl: 'High-sensitivity Cardiac Troponin I (cTnI) and Troponin T (cTnT) are the primary gold-standard diagnostic biomarkers for acute coronary syndromes (myocardial infarction), rising within 2-4 hours post-ischemia.',
    relatedTerms: ['Sarcomere', 'Cardiomyocyte', 'Action Potential']
  },
  {
    id: 'vasoconstriction',
    term: 'Vasoconstriction',
    aliases: ['vasoconstrictor', 'vasoconstricting', 'arteriolar constriction', 'vascular resistance'],
    category: 'Physiology',
    level: 'school',
    pronunciation: '/ˌveɪ.zoʊ.kənˈstrɪk.ʃən/',
    etymology: 'Latin vas (vessel) + constringere (to draw tight together)',
    definition: 'The narrowing of blood vessel lumens resulting from contraction of the vascular smooth muscle layer within vessel walls (particularly in arterioles).',
    mechanism: 'Stimulated by Norepinephrine (α1-adrenergic), Endothelin-1, Angiotensin II, and Vasopressin (V1). Increases intracellular Ca²⁺ via IP3 pathway, activating Myosin Light Chain Kinase (MLCK). By Poiseuille\'s Law, resistance is inversely proportional to radius to the 4th power (R ∝ 1/r⁴).',
    clinicalPearl: 'Raynaud phenomenon is an exaggerated vasospastic response of digital arterioles to cold or emotional stress, causing sharp demarcated color changes from white (ischemia) to blue (hypoxia) to red (reperfusion).',
    relatedTerms: ['Renin-Angiotensin-Aldosterone System (RAAS)', 'Homeostasis', 'Glomerular Filtration Rate (GFR)']
  }
];

// Map of lower-cased lookup terms to the canonical GlossaryTerm
const glossaryLookupMap = new Map<string, GlossaryTerm>();

// Populate lookup map with canonical terms and aliases
BIOLOGY_GLOSSARY.forEach((item) => {
  glossaryLookupMap.set(item.term.toLowerCase(), item);
  glossaryLookupMap.set(item.id.toLowerCase(), item);
  item.aliases.forEach((alias) => {
    glossaryLookupMap.set(alias.toLowerCase(), item);
  });
});

/**
 * Finds a glossary term by exact or alias match (case-insensitive)
 */
export function findGlossaryTerm(rawTerm: string): GlossaryTerm | undefined {
  if (!rawTerm) return undefined;
  const clean = rawTerm.trim().toLowerCase();
  return glossaryLookupMap.get(clean);
}

/**
 * Generates an optimized sorted list of all search strings for regex compilation
 */
export function getSortedGlossaryKeywords(): { keyword: string; termId: string }[] {
  const list: { keyword: string; termId: string }[] = [];
  
  BIOLOGY_GLOSSARY.forEach((item) => {
    list.push({ keyword: item.term, termId: item.id });
    item.aliases.forEach((alias) => {
      // Only include multi-character meaningful keywords to prevent matching short words like 'as', 'or', 'in'
      if (alias.length >= 3) {
        list.push({ keyword: alias, termId: item.id });
      }
    });
  });

  // Sort by length descending so longer phrases match before substrings (e.g. "Action Potential" before "Action")
  list.sort((a, b) => b.keyword.length - a.keyword.length);
  return list;
}
